### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by guikebr** [hnvn/flutter_pattern_formatter#3]
Because every version of pattern_formatter depends on intl ^0.15.7 and every version of flutter_localizations from sdk depends on intl 0.16.0, pattern_formatter is incompatible with flutter_localizations from sdk.
So, because localize depends on both flutter_localizations any from sdk and pattern_formatter ^0.0.3, version solving failed.
pub get failed (1; So, because localize depends on both flutter_localizations any from sdk and pattern_formatter ^0.0.3, version solving failed.)

**Comment by hnvn** [comment]
What flutter version are you running? I still work well with Flutter v1.9.1+hotfix.6

**Comment by guikebr** [comment]
Thanks man! I solved my problem by switching to version 1.9.1
