### ISSUE TITLE
Incompatibility flutter 1.12.13-hotfixes

### ISSUE THREAD

**Issue by guikebr** [hnvn/flutter_pattern_formatter#4]
Because localize depends on flutter_localizations any from sdk which depends on intl 0.16.0, intl 0.16.0 is required.
So, because localize depends on intl ^0.15.7, version solving failed.
pub get failed (1; So, because localize depends on intl ^0.15.7, version solving failed.)

**Comment by Jamalianpour** [comment]
I have same problem.

**Comment by athlona64** [comment]
i have same problem

**Comment by hnvn** [comment]
fixed in v1.0.1
