### ISSUE TITLE
Feature: Limit the number of decimal digits

### ISSUE THREAD

**Issue by codegrue** [hnvn/flutter_pattern_formatter#6]
For example, could limit to two. Currently, it seems to stop at three digits.

**Comment by alfredjingle** [comment]
You can do this by using a custom formatter, e.g. for the thousands formatter you can do the following to limit the number of dp to 2L

`ThousandsFormatter(
      allowFraction: true,
      formatter: NumberFormat(
          '###,###.##',
 ))`

**Comment by codegrue** [comment]
Confirmed works for English formatted numbers. Other locales do not work. Have an alternate feature request to support this.
